### ISSUE TITLE
testibg with feather m4 w cpy 6.2 release, no response

### ISSUE THREAD

**Issue by ladyada** [jamesbowman/CircuitPython_bteve#1]
hi there, im trying out the circuitpython-on-feather-m4 with the feather shield and getting...

```
Traceback (most recent call last):
  File "code.py", line 4, in <module>
  File "bteve/gameduino.py", line 178, in init
AssertionError: No response - is device attached?
```

can you try a feather m4 with 6.2 release?

**Comment by ladyada** [comment]
tested with 6.2 beta 3 (the first release with the feather m4 support) - same thing

**Comment by jamesbowman** [comment]
Right, I'm running with the 6.2/

This error message means that it couldn't detect the EVE or Dazzler at all.

There's some improvements to the startup sequence in the latest version of the bteve library. The easiest way to get everything in one go is this zip:

https://excamera.com/files/rotablinka-complete.zip

**Comment by ladyada** [comment]
ahh ok it turns out you cannot use stacking headers. something about the sockets are very picky about the width of the contacts. ill make a note of it!

**Comment by ladyada** [comment]
ahh i spoke too soon (and also had two boards i was testing with)
i have a board that still will not respond consistantly. maybe the library needs more hardware resets/retries? you'll get more data soon one way or another!

**Comment by jamesbowman** [comment]
The latest version of the code does a hard reset of the FPGA core, then waits 0.6s for it to finish loading and boot:

https://github.com/jamesbowman/CircuitPython_bteve/blob/main/bteve/gameduino_circuitpython.py#L39-L42

**Comment by ladyada** [comment]
that might help? it doesnt seem to hurt...
